from lib.forum_engine import Template
from lib.network_tools import NetworkTools

class Crawler(Template):
	NETWORK_TOOLS = NetworkTools(use_proxy=False)
	TEMPLATE = "crawler.arct"
	TEST_TEMPLATE = "crawler_test.arct"
	DB_SERVER_ADDRESS = "mongo:27017"
	DB_SERVER_NAME = "levelupgames"
	CRAWLER_NAME = "levelupgames crawler"
	LINK_TO_CRAWL = [
		"http://forums.levelupgames.ph/index.php?/forum/2-level-up-news/",
		"http://forums.levelupgames.ph/index.php?/forum/220-level-up-live/",
		"http://forums.levelupgames.ph/index.php?/forum/123-suggestions/",
		"http://forums.levelupgames.ph/index.php?/forum/143-grand-chase/",
		"http://forums.levelupgames.ph/index.php?/forum/146-rohan/",
		"http://forums.levelupgames.ph/index.php?/forum/144-perfect-world/",
		"http://forums.levelupgames.ph/index.php?/forum/141-flyff/",
		"http://forums.levelupgames.ph/index.php?/forum/379-ragnarok/",
		"http://forums.levelupgames.ph/index.php?/forum/490-bounty-hounds/",
		"http://forums.levelupgames.ph/index.php?/forum/567-events/",
		"http://forums.levelupgames.ph/index.php?/forum/570-server-status/",
		"http://forums.levelupgames.ph/index.php?/forum/557-general-discussion/",
		"http://forums.levelupgames.ph/index.php?/forum/571-feedback/",
		"http://forums.levelupgames.ph/index.php?/forum/559-boxer/",
		"http://forums.levelupgames.ph/index.php?/forum/562-blitzer/",
		"http://forums.levelupgames.ph/index.php?/forum/560-slugger/",
		"http://forums.levelupgames.ph/index.php?/forum/561-fire-fighter/",
		"http://forums.levelupgames.ph/index.php?/forum/563-rocker/",
		"http://forums.levelupgames.ph/index.php?/forum/527-announcements/",
		"http://forums.levelupgames.ph/index.php?/forum/550-galgarons-edict/",
		"http://forums.levelupgames.ph/index.php?/forum/551-updates-and-events/",
		"http://forums.levelupgames.ph/index.php?/forum/537-server-update/",
		"http://forums.levelupgames.ph/index.php?/forum/538-patch-notes/",
		"http://forums.levelupgames.ph/index.php?/forum/576-ingame-events/",
		"http://forums.levelupgames.ph/index.php?/forum/607-galgaron-battle-arena-championship/",
		"http://forums.levelupgames.ph/index.php?/forum/608-official-announcement/",
		"http://forums.levelupgames.ph/index.php?/forum/539-guides-and-walkthrough/",
		"http://forums.levelupgames.ph/index.php?/forum/588-news/",
		"http://forums.levelupgames.ph/index.php?/forum/589-server-status/",
		"http://forums.levelupgames.ph/index.php?/forum/590-patch-notes/",
		"http://forums.levelupgames.ph/index.php?/forum/627-audition-full-client-and-patch/",
		"http://forums.levelupgames.ph/index.php?/forum/599-event-discussion/",
		"http://forums.levelupgames.ph/index.php?/forum/600-general-discussions/",
		"http://forums.levelupgames.ph/index.php?/forum/602-announcement-discussion/",
		"http://forums.levelupgames.ph/index.php?/forum/603-bug-reports/",
		"http://forums.levelupgames.ph/index.php?/forum/604-technical-concerns/",
		"http://forums.levelupgames.ph/index.php?/forum/614-official-announcements/",
		"http://forums.levelupgames.ph/index.php?/forum/480-server-status/",
		"http://forums.levelupgames.ph/index.php?/forum/618-emporium/",
		"http://forums.levelupgames.ph/index.php?/forum/481-bulletin-board-discussions/",
		"http://forums.levelupgames.ph/index.php?/forum/619-the-academy/",
		"http://forums.levelupgames.ph/index.php?/forum/500-guides/",
		"http://forums.levelupgames.ph/index.php?/forum/620-tips-and-tricks/",
		"http://forums.levelupgames.ph/index.php?/forum/492-combat-tactical-units/",
		"http://forums.levelupgames.ph/index.php?/forum/485-bio-engineer/",
		"http://forums.levelupgames.ph/index.php?/forum/486-gunner/",
		"http://forums.levelupgames.ph/index.php?/forum/487-sentinel/",
		"http://forums.levelupgames.ph/index.php?/forum/488-soldier/",
		"http://forums.levelupgames.ph/index.php?/forum/489-reaper/",
		"http://forums.levelupgames.ph/index.php?/forum/493-squad-assembly/",
		"http://forums.levelupgames.ph/index.php?/forum/514-bazaar/",
		"http://forums.levelupgames.ph/index.php?/forum/483-feedbacks-comments-and-suggestions/",
		"http://forums.levelupgames.ph/index.php?/forum/491-technical-support/",
		"http://forums.levelupgames.ph/index.php?/forum/623-bug-reports/",
		"http://forums.levelupgames.ph/index.php?/forum/163-official-announcements/",
		"http://forums.levelupgames.ph/index.php?/forum/164-game-status/",
		"http://forums.levelupgames.ph/index.php?/forum/165-live-events/",
		"http://forums.levelupgames.ph/index.php?/forum/167-patch-notes/",
		"http://forums.levelupgames.ph/index.php?/forum/431-manual-patch/",
		"http://forums.levelupgames.ph/index.php?/forum/464-official-announcements/",
		"http://forums.levelupgames.ph/index.php?/forum/528-tournament-discussions/",
		"http://forums.levelupgames.ph/index.php?/forum/171-tournament-flashbacks",
		"http://forums.levelupgames.ph/index.php?/forum/175-bulletin-board-discussions/",
		"http://forums.levelupgames.ph/index.php?/forum/172-new-to-grand-chase-ask-here/",
		"http://forums.levelupgames.ph/index.php?/forum/173-tips-and-tricks/",
		"http://forums.levelupgames.ph/index.php?/forum/465-awesome-replays/",
		"http://forums.levelupgames.ph/index.php?/forum/443-pet-corner/",
		"http://forums.levelupgames.ph/index.php?/forum/148-elesis/",
		"http://forums.levelupgames.ph/index.php?/forum/149-lire/",
		"http://forums.levelupgames.ph/index.php?/forum/150-arme/",
		"http://forums.levelupgames.ph/index.php?/forum/151-ronan/",
		"http://forums.levelupgames.ph/index.php?/forum/152-lass/",
		"http://forums.levelupgames.ph/index.php?/forum/153-ryan/",
		"http://forums.levelupgames.ph/index.php?/forum/154-amy/",
		"http://forums.levelupgames.ph/index.php?/forum/183-jin/",
		"http://forums.levelupgames.ph/index.php?/forum/155-sieghart/",
		"http://forums.levelupgames.ph/index.php?/forum/156-mari/",
		"http://forums.levelupgames.ph/index.php?/forum/391-dio/",
		"http://forums.levelupgames.ph/index.php?/forum/435-zero/",
		"http://forums.levelupgames.ph/index.php?/forum/445-ley/",
		"http://forums.levelupgames.ph/index.php?/forum/499-luxus/",
		"http://forums.levelupgames.ph/index.php?/forum/529-rin/",
		"http://forums.levelupgames.ph/index.php?/forum/552-asin/",
		"http://forums.levelupgames.ph/index.php?/forum/572-lime/",
		"http://forums.levelupgames.ph/index.php?/forum/632-edel/",
		"http://forums.levelupgames.ph/index.php?/forum/160-grand-chase-guilds/",
		"http://forums.levelupgames.ph/index.php?/forum/498-bermesiah-taverns/",
		"http://forums.levelupgames.ph/index.php?/forum/433-player-of-the-week/",
		"http://forums.levelupgames.ph/index.php?/forum/174-gms-corner/",
		"http://forums.levelupgames.ph/index.php?/forum/158-feedbacks-comments-and-suggestions/",
		"http://forums.levelupgames.ph/index.php?/forum/177-technical-inquiries/",
		"http://forums.levelupgames.ph/index.php?/forum/178-bug-reports/",
		"http://forums.levelupgames.ph/index.php?/forum/506-important-news-and-announcements/",
		"http://forums.levelupgames.ph/index.php?/forum/578-the-song-of-shadow/",
		"http://forums.levelupgames.ph/index.php?/forum/520-awakening-of-the-guardians/",
		"http://forums.levelupgames.ph/index.php?/forum/216-server-update/",
		"http://forums.levelupgames.ph/index.php?/forum/501-in-game-events/",
		"http://forums.levelupgames.ph/index.php?/forum/502-live-events/",
		"http://forums.levelupgames.ph/index.php?/forum/504-forum-events/",
		"http://forums.levelupgames.ph/index.php?/forum/505-item-mall-updates/",
		"http://forums.levelupgames.ph/index.php?/forum/611-official-announcement/",
		"http://forums.levelupgames.ph/index.php?/forum/185-tournament-discussion/",
		"http://forums.levelupgames.ph/index.php?/forum/217-xia-fengs-mailbox/",
		"http://forums.levelupgames.ph/index.php?/forum/513-featured-players/",
		"http://forums.levelupgames.ph/index.php?/forum/43-gameplay-discussions/",
		"http://forums.levelupgames.ph/index.php?/forum/45-feedback-and-suggestions/",
		"http://forums.levelupgames.ph/index.php?/forum/46-technical-inquiries/",
		"http://forums.levelupgames.ph/index.php?/forum/186-guides-and-faqs/",
		"http://forums.levelupgames.ph/index.php?/forum/48-wuxia/",
		"http://forums.levelupgames.ph/index.php?/forum/49-fashih/",
		"http://forums.levelupgames.ph/index.php?/forum/50-yaoshou/",
		"http://forums.levelupgames.ph/index.php?/forum/51-yaojing/",
		"http://forums.levelupgames.ph/index.php?/forum/52-yumang/",
		"http://forums.levelupgames.ph/index.php?/forum/53-yuling/",
		"http://forums.levelupgames.ph/index.php?/forum/54-wushih/",
		"http://forums.levelupgames.ph/index.php?/forum/55-xishou/",
		"http://forums.levelupgames.ph/index.php?/forum/57-tigers-den/",
		"http://forums.levelupgames.ph/index.php?/forum/58-dragons-lair/",
		"http://forums.levelupgames.ph/index.php?/forum/59-serpents-burrow/",
		"http://forums.levelupgames.ph/index.php?/forum/88-news-and-announcements/",
		"http://forums.levelupgames.ph/index.php?/forum/130-server-status/",
		"http://forums.levelupgames.ph/index.php?/forum/180-forum-events/",
		"http://forums.levelupgames.ph/index.php?/forum/512-featured-players/",
		"http://forums.levelupgames.ph/index.php?/forum/131-game-parlor-winners/",
		"http://forums.levelupgames.ph/index.php?/forum/89-gathering-hall/",
		"http://forums.levelupgames.ph/index.php?/forum/184-discussion-threads/",
		"http://forums.levelupgames.ph/index.php?/forum/360-submission-threads/",
		"http://forums.levelupgames.ph/index.php?/forum/90-comments-and-suggestions/",
		"http://forums.levelupgames.ph/index.php?/forum/91-technical-help-and-troubleshooting/",
		"http://forums.levelupgames.ph/index.php?/forum/111-the-story-of-rohan/",
		"http://forums.levelupgames.ph/index.php?/forum/102-guides-and-walkthroughs/",
		"http://forums.levelupgames.ph/index.php?/forum/187-newbie-central/",
		"http://forums.levelupgames.ph/index.php?/forum/103-human/",
		"http://forums.levelupgames.ph/index.php?/forum/104-elf/",
		"http://forums.levelupgames.ph/index.php?/forum/105-half-elf/",
		"http://forums.levelupgames.ph/index.php?/forum/106-dark-elf/",
		"http://forums.levelupgames.ph/index.php?/forum/107-dhan/",
		"http://forums.levelupgames.ph/index.php?/forum/108-dekan/",
		"http://forums.levelupgames.ph/index.php?/forum/109-giant/",
		"http://forums.levelupgames.ph/index.php?/forum/92-server-discussions/",
		"http://forums.levelupgames.ph/index.php?/forum/93-neo-edoneh/",
		"http://forums.levelupgames.ph/index.php?/forum/99-einhoren/",
		"http://forums.levelupgames.ph/index.php?/forum/382-akkarna/",
		"http://forums.levelupgames.ph/index.php?/forum/221-important-announcements/",
		"http://forums.levelupgames.ph/index.php?/forum/226-game-status/",
		"http://forums.levelupgames.ph/index.php?/forum/222-in-game-events/",
		"http://forums.levelupgames.ph/index.php?/forum/227-live-events/",
		"http://forums.levelupgames.ph/index.php?/forum/223-flyff-shop/",
		"http://forums.levelupgames.ph/index.php?/forum/228-forum-events/",
		"http://forums.levelupgames.ph/index.php?/forum/398-featured-players/",
		"http://forums.levelupgames.ph/index.php?/forum/66-talk-flyff/",
		"http://forums.levelupgames.ph/index.php?/forum/475-vagrants-corner/",
		"http://forums.levelupgames.ph/index.php?/forum/444-post-box/",
		"http://forums.levelupgames.ph/index.php?/forum/67-saint-morning-library/",
		"http://forums.levelupgames.ph/index.php?/forum/73-lions%e2%80%99-den-tavern/",
		"http://forums.levelupgames.ph/index.php?/forum/72-magic%e2%80%99s-tower/",
		"http://forums.levelupgames.ph/index.php?/forum/70-sharpshooters%e2%80%99-haven/",
		"http://forums.levelupgames.ph/index.php?/forum/71-spirit-masters-order/",
		"http://forums.levelupgames.ph/index.php?/forum/460-ishirut/",
		"http://forums.levelupgames.ph/index.php?/forum/530-genesis/",
		"http://forums.levelupgames.ph/index.php?/forum/477-feedbacks-comments-and-suggestions/",
		"http://forums.levelupgames.ph/index.php?/forum/479-bug-reports/",
		"http://forums.levelupgames.ph/index.php?/forum/240-technical-inquiries/",
		"http://forums.levelupgames.ph/index.php?/forum/250-news/",
		"http://forums.levelupgames.ph/index.php?/forum/251-server-status/",
		"http://forums.levelupgames.ph/index.php?/forum/375-patch-notes/",
		"http://forums.levelupgames.ph/index.php?/forum/364-promos/",
		"http://forums.levelupgames.ph/index.php?/forum/534-on-ground-event/",
		"http://forums.levelupgames.ph/index.php?/forum/365-in-game-events/",
		"http://forums.levelupgames.ph/index.php?/forum/366-npc-events/",
		"http://forums.levelupgames.ph/index.php?/forum/367-friday-night-ragnarok/",
		"http://forums.levelupgames.ph/index.php?/forum/368-forum-event/",
		"http://forums.levelupgames.ph/index.php?/forum/369-event-discussion/",
		"http://forums.levelupgames.ph/index.php?/forum/397-prize-status/",
		"http://forums.levelupgames.ph/index.php?/forum/371-featured-item-of-the-week/",
		"http://forums.levelupgames.ph/index.php?/forum/372-gm-anaels-shopping-list/",
		"http://forums.levelupgames.ph/index.php?/forum/373-armory-of-the-gods-discussion/",
		"http://forums.levelupgames.ph/index.php?/forum/583-rwc-2014-discussion-thread/",
		"http://forums.levelupgames.ph/index.php?/forum/309-sakray-server-and-future-updates/",
		"http://forums.levelupgames.ph/index.php?/forum/380-technical-inquiries/",
		"http://forums.levelupgames.ph/index.php?/forum/392-new-loki/",
		"http://forums.levelupgames.ph/index.php?/forum/515-new-iris/"
        ]
	COUNTRY = "PHL"
	THREAD_XPATH = "//table[@class='ipb_table topic_list']//tr[re:test(@id,'trow_*')]"
	THREAD_LINK_XPATH = ".//a[@class='topic_title']/@href"
	LAST_PAGE_XPATH = "//ul[@class='pagination left']//a[@rel='last']/@href"
	PREV_XPATH = "//ul[@class='pagination left']//a[@rel='prev']/@href"
	POST_XPATH = "//div[re:test(@id,'post_id_*')]"
	FIELDS = [ 
		{"published_date": {
			"single": True,
			"data_type": "date",
			"concat": True,
			"xpath":".//abbr[@class='published']/text()"
		}},
		{"author_name":{
			"single":True,
			"data_type": "string",
			"concat":True,
			"xpath": ".//span[@class='author vcard']/a[@class='url fn']/text()"
		}},
		{"content":{
			"single":True,
			"data_type": "string",
			"concat":True,
			"xpath":".//div[@class='post entry-content ']//text()"
		}},
		{"permalink": {
			"single": True,
			"data_type": "url",
			"concat": False,
			"xpath": ".//span[@class='post_id']//a[re:test(@title,'Link to post*')]/@href"
		}},
		{"title":{
			"single":True,
			"data_type": "string",
			"concat":False,
			"xpath":"//h2[@class='maintitle']//span[@class='main_topic_title']/text()[1]"
		}}       
	]
	CONDITIONS={
		"has_to_have_content":{
			"condition":'"content" in document',
			"exception":'"Content is not defined"'
		},
		"content_cannot_be_empty":{
			"condition":'len(document["content"]) > 0',
			"exception":'"Content cannot be empty"'
		}
	}
#end class
