from lib.forum_engine import Template
from lib.network_tools import NetworkTools

class Crawler(Template):
	NETWORK_TOOLS = NetworkTools(use_proxy=False)
	TEMPLATE = "crawler.arct"
	TEST_TEMPLATE = "crawler_test.arct"
	DB_SERVER_ADDRESS = "mongo:27017"
	DB_SERVER_NAME = "meraforum"
	CRAWLER_NAME = "meraforum crawler"
	LINK_TO_CRAWL = [
		"http://www.meraforum.com/forumdisplay.php?f=4",
		"http://www.meraforum.com/forumdisplay.php?f=5",
		"http://www.meraforum.com/forumdisplay.php?f=119",
		"http://www.meraforum.com/forumdisplay.php?f=6",
		"http://www.meraforum.com/forumdisplay.php?f=7",
		"http://www.meraforum.com/forumdisplay.php?f=94",
		"http://www.meraforum.com/forumdisplay.php?f=88",
		"http://www.meraforum.com/forumdisplay.php?f=128",
		"http://www.meraforum.com/forumdisplay.php?f=9",
		"http://www.meraforum.com/forumdisplay.php?f=10",
		"http://www.meraforum.com/forumdisplay.php?f=11",
		"http://www.meraforum.com/forumdisplay.php?f=12",
		"http://www.meraforum.com/forumdisplay.php?f=122",
		"http://www.meraforum.com/forumdisplay.php?f=120",
		"http://www.meraforum.com/forumdisplay.php?f=150",
		"http://www.meraforum.com/forumdisplay.php?f=59",
		"http://www.meraforum.com/forumdisplay.php?f=101",
		"http://www.meraforum.com/forumdisplay.php?f=111",
		"http://www.meraforum.com/forumdisplay.php?f=135",
		"http://www.meraforum.com/forumdisplay.php?f=126",
		"http://www.meraforum.com/forumdisplay.php?f=134",
		"http://www.meraforum.com/forumdisplay.php?f=14",
		"http://www.meraforum.com/forumdisplay.php?f=207",
		"http://www.meraforum.com/forumdisplay.php?f=15",
		"http://www.meraforum.com/forumdisplay.php?f=99",
		"http://www.meraforum.com/forumdisplay.php?f=16",
		"http://www.meraforum.com/forumdisplay.php?f=17",
		"http://www.meraforum.com/forumdisplay.php?f=136",
		"http://www.meraforum.com/forumdisplay.php?f=183",
		"http://www.meraforum.com/forumdisplay.php?f=198",
		"http://www.meraforum.com/forumdisplay.php?f=67",
		"http://www.meraforum.com/forumdisplay.php?f=89",
		"http://www.meraforum.com/forumdisplay.php?f=96",
		"http://www.meraforum.com/forumdisplay.php?f=18",
		"http://www.meraforum.com/forumdisplay.php?f=63",
		"http://www.meraforum.com/forumdisplay.php?f=213",
		"http://www.meraforum.com/forumdisplay.php?f=20",
		"http://www.meraforum.com/forumdisplay.php?f=131",
		"http://www.meraforum.com/forumdisplay.php?f=21",
		"http://www.meraforum.com/forumdisplay.php?f=22",
		"http://www.meraforum.com/forumdisplay.php?f=132",
		"http://www.meraforum.com/forumdisplay.php?f=23",
		"http://www.meraforum.com/forumdisplay.php?f=204",
		"http://www.meraforum.com/forumdisplay.php?f=210",
		"http://www.meraforum.com/forumdisplay.php?f=57",
		"http://www.meraforum.com/forumdisplay.php?f=66",
		"http://www.meraforum.com/forumdisplay.php?f=24",
		"http://www.meraforum.com/forumdisplay.php?f=27",
		"http://www.meraforum.com/forumdisplay.php?f=28",
		"http://www.meraforum.com/forumdisplay.php?f=30",
		"http://www.meraforum.com/forumdisplay.php?f=31",
		"http://www.meraforum.com/forumdisplay.php?f=32",
		"http://www.meraforum.com/forumdisplay.php?f=60",
		"http://www.meraforum.com/forumdisplay.php?f=68",
		"http://www.meraforum.com/forumdisplay.php?f=83",
		"http://www.meraforum.com/forumdisplay.php?f=93",
		"http://www.meraforum.com/forumdisplay.php?f=25",
		"http://www.meraforum.com/forumdisplay.php?f=184",
		"http://www.meraforum.com/forumdisplay.php?f=163",
		"http://www.meraforum.com/forumdisplay.php?f=160",
		"http://www.meraforum.com/forumdisplay.php?f=161",
		"http://www.meraforum.com/forumdisplay.php?f=162",
		"http://www.meraforum.com/forumdisplay.php?f=164",
		"http://www.meraforum.com/forumdisplay.php?f=165",
		"http://www.meraforum.com/forumdisplay.php?f=180",
		"http://www.meraforum.com/forumdisplay.php?f=186",
		"http://www.meraforum.com/forumdisplay.php?f=185",
		"http://www.meraforum.com/forumdisplay.php?f=214",
		"http://www.meraforum.com/forumdisplay.php?f=208",
		"http://www.meraforum.com/forumdisplay.php?f=211",
		"http://www.meraforum.com/forumdisplay.php?f=73",
		"http://www.meraforum.com/forumdisplay.php?f=71",
		"http://www.meraforum.com/forumdisplay.php?f=72",
		"http://www.meraforum.com/forumdisplay.php?f=26",
		"http://www.meraforum.com/forumdisplay.php?f=29",
		"http://www.meraforum.com/forumdisplay.php?f=191",
		"http://www.meraforum.com/forumdisplay.php?f=196",
		"http://www.meraforum.com/forumdisplay.php?f=195",
		"http://www.meraforum.com/forumdisplay.php?f=193",
		"http://www.meraforum.com/forumdisplay.php?f=194",
		"http://www.meraforum.com/forumdisplay.php?f=197",
		"http://www.meraforum.com/forumdisplay.php?f=192",
		"http://www.meraforum.com/forumdisplay.php?f=166",
		"http://www.meraforum.com/forumdisplay.php?f=209",
		"http://www.meraforum.com/forumdisplay.php?f=175",
		"http://www.meraforum.com/forumdisplay.php?f=167",
		"http://www.meraforum.com/forumdisplay.php?f=170",
		"http://www.meraforum.com/forumdisplay.php?f=169",
		"http://www.meraforum.com/forumdisplay.php?f=168",
		"http://www.meraforum.com/forumdisplay.php?f=171",
		"http://www.meraforum.com/forumdisplay.php?f=172",
		"http://www.meraforum.com/forumdisplay.php?f=174",
		"http://www.meraforum.com/forumdisplay.php?f=177",
		"http://www.meraforum.com/forumdisplay.php?f=176",
		"http://www.meraforum.com/forumdisplay.php?f=178",
		"http://www.meraforum.com/forumdisplay.php?f=179",
		"http://www.meraforum.com/forumdisplay.php?f=181",
		"http://www.meraforum.com/forumdisplay.php?f=34",
		"http://www.meraforum.com/forumdisplay.php?f=35",
		"http://www.meraforum.com/forumdisplay.php?f=36",
		"http://www.meraforum.com/forumdisplay.php?f=38",
		"http://www.meraforum.com/forumdisplay.php?f=39",
		"http://www.meraforum.com/forumdisplay.php?f=84",
		"http://www.meraforum.com/forumdisplay.php?f=138",
		"http://www.meraforum.com/forumdisplay.php?f=137",
		"http://www.meraforum.com/forumdisplay.php?f=98",
		"http://www.meraforum.com/forumdisplay.php?f=112",
		"http://www.meraforum.com/forumdisplay.php?f=114",
		"http://www.meraforum.com/forumdisplay.php?f=65",
		"http://www.meraforum.com/forumdisplay.php?f=41",
		"http://www.meraforum.com/forumdisplay.php?f=212",
		"http://www.meraforum.com/forumdisplay.php?f=125",
		"http://www.meraforum.com/forumdisplay.php?f=127",
		"http://www.meraforum.com/forumdisplay.php?f=133",
		"http://www.meraforum.com/forumdisplay.php?f=124",
		"http://www.meraforum.com/forumdisplay.php?f=130",
		"http://www.meraforum.com/forumdisplay.php?f=123",
		"http://www.meraforum.com/forumdisplay.php?f=129",
		"http://www.meraforum.com/forumdisplay.php?f=76",
		"http://www.meraforum.com/forumdisplay.php?f=42",
		"http://www.meraforum.com/forumdisplay.php?f=43",
		"http://www.meraforum.com/forumdisplay.php?f=44",
		"http://www.meraforum.com/forumdisplay.php?f=55",
		"http://www.meraforum.com/forumdisplay.php?f=81",
		"http://www.meraforum.com/forumdisplay.php?f=115",
		"http://www.meraforum.com/forumdisplay.php?f=206",
		"http://www.meraforum.com/forumdisplay.php?f=85",
		"http://www.meraforum.com/forumdisplay.php?f=86",
		"http://www.meraforum.com/forumdisplay.php?f=90",
		"http://www.meraforum.com/forumdisplay.php?f=107",
		"http://www.meraforum.com/forumdisplay.php?f=82",
		"http://www.meraforum.com/forumdisplay.php?f=205",
		"http://www.meraforum.com/forumdisplay.php?f=109",
		"http://www.meraforum.com/forumdisplay.php?f=92",
		"http://www.meraforum.com/forumdisplay.php?f=108",
		"http://www.meraforum.com/forumdisplay.php?f=46",
		"http://www.meraforum.com/forumdisplay.php?f=47",
		"http://www.meraforum.com/forumdisplay.php?f=48",
		"http://www.meraforum.com/forumdisplay.php?f=64",
		"http://www.meraforum.com/forumdisplay.php?f=152",
		"http://www.meraforum.com/forumdisplay.php?f=153",
		"http://www.meraforum.com/forumdisplay.php?f=154",
		"http://www.meraforum.com/forumdisplay.php?f=155",
		"http://www.meraforum.com/forumdisplay.php?f=156",
		"http://www.meraforum.com/forumdisplay.php?f=157",
		"http://www.meraforum.com/forumdisplay.php?f=158",
		"http://www.meraforum.com/forumdisplay.php?f=159",
		"http://www.meraforum.com/forumdisplay.php?f=199",
		"http://www.meraforum.com/forumdisplay.php?f=202",
		"http://www.meraforum.com/forumdisplay.php?f=201",
		"http://www.meraforum.com/forumdisplay.php?f=200",
		"http://www.meraforum.com/forumdisplay.php?f=203",
		"http://www.meraforum.com/forumdisplay.php?f=50",
		"http://www.meraforum.com/forumdisplay.php?f=218",
		"http://www.meraforum.com/forumdisplay.php?f=216",
		"http://www.meraforum.com/forumdisplay.php?f=217",
		"http://www.meraforum.com/forumdisplay.php?f=52",
		"http://www.meraforum.com/forumdisplay.php?f=143",
		"http://www.meraforum.com/forumdisplay.php?f=144",
		"http://www.meraforum.com/forumdisplay.php?f=149",
		"http://www.meraforum.com/forumdisplay.php?f=151",
		"http://www.meraforum.com/forumdisplay.php?f=145",
		"http://www.meraforum.com/forumdisplay.php?f=148",
		"http://www.meraforum.com/forumdisplay.php?f=87",
		"http://www.meraforum.com/forumdisplay.php?f=139",
		"http://www.meraforum.com/forumdisplay.php?f=141",
		"http://www.meraforum.com/forumdisplay.php?f=142",
		"http://www.meraforum.com/forumdisplay.php?f=215",
		"http://www.meraforum.com/forumdisplay.php?f=54",
		"http://www.meraforum.com/forumdisplay.php?f=70",
		"http://www.meraforum.com/forumdisplay.php?f=220"
        ]
	COUNTRY = "PHL"
	THREAD_XPATH = "//td[re:test(@id,'td_threadtitle_*')]"
	THREAD_LINK_XPATH = ".//a[re:test(@id,'thread_title_*')]/@href"
	
	LAST_PAGE_XPATH = "(//div[@class='pagenav']//td[@class='vbmenu_control'])[last()]//preceding::a[re:test(@title,'Last Page*') or re:test(@title,'Show results*')][1]/@href"
	PREV_XPATH = "//div[@class='pagenav']//a[re:test(@title,'Prev Page*')]/@href"
	POST_XPATH = "//table[re:test(@id,'post*')]"
	FIELDS = [ 
		{"published_date": {
			"single": True,
			"data_type": "date",
			"concat": False,
			"xpath":".//td[re:test(@id,'td_post_*')]/div[@class='smallfont']/text()[last()-1]"
		}},
		{"author_name":{
			"single":True,
			"data_type": "string",
			"concat":False,
			"xpath": ".//a[@class='bigusername']//text()"
		}},
		{"content":{
			"single":True,
			"data_type": "string",
			"concat":True,
			"xpath":".//div[re:test(@id,'post_message_*')]//div[1]//text()"
		}},
		{"permalink": {
			"single": True,
			"data_type": "url",
			"concat": False,
			"xpath": ".//preceding::a[re:test(@id,'postcount*')]/@href"
		}},
		{"title":{
			"single":True,
			"data_type": "string",
			"concat":False,
			"xpath":"//div[@class='page_left']//a[3]/following::text()[1]"
		}}       
	]
	CONDITIONS={
		"has_to_have_content":{
			"condition":'"content" in document',
			"exception":'"Content is not defined"'
		},
		"content_cannot_be_empty":{
			"condition":'len(document["content"]) > 0',
			"exception":'"Content cannot be empty"'
		}
	}
#end class
