from lib.forum_engine import Template
from lib.network_tools import NetworkTools

class Crawler(Template):
	NETWORK_TOOLS = NetworkTools(use_proxy=False)
	TEMPLATE = "crawler.arct"
	TEST_TEMPLATE = "crawler_test.arct"
	DB_SERVER_ADDRESS = "mongo:27017"
	DB_SERVER_NAME = "smartcarofamerica"
	CRAWLER_NAME = "smartcarofamerica crawler"
	LINK_TO_CRAWL = [
		"http://www.smartcarofamerica.com/forums/f221/",
		"http://www.smartcarofamerica.com/forums/f2/",
		"http://www.smartcarofamerica.com/forums/f4/",
		"http://www.smartcarofamerica.com/forums/f53/",
		"http://www.smartcarofamerica.com/forums/f3/",
		"http://www.smartcarofamerica.com/forums/f3/",
		"http://www.smartcarofamerica.com/forums/f188/",
		"http://www.smartcarofamerica.com/forums/f200/",
		"http://www.smartcarofamerica.com/forums/f15/",
		"http://www.smartcarofamerica.com/forums/f65/",
		"http://www.smartcarofamerica.com/forums/f179/",
		"http://www.smartcarofamerica.com/forums/f180/",
		"http://www.smartcarofamerica.com/forums/f181/",
		"http://www.smartcarofamerica.com/forums/f182/",
		"http://www.smartcarofamerica.com/forums/f314/",
		"http://www.smartcarofamerica.com/forums/f506/",
		"http://www.smartcarofamerica.com/forums/f313/",
		"http://www.smartcarofamerica.com/forums/f202/",
		"http://www.smartcarofamerica.com/forums/f281/",
		"http://www.smartcarofamerica.com/forums/f289/",
		"http://www.smartcarofamerica.com/forums/f241/",
		"http://www.smartcarofamerica.com/forums/f257/",
		"http://www.smartcarofamerica.com/forums/f249/",
		"http://www.smartcarofamerica.com/forums/f234/",
		"http://www.smartcarofamerica.com/forums/f212/",
		"http://www.smartcarofamerica.com/forums/f218/",
		"http://www.smartcarofamerica.com/forums/f151/",
		"http://www.smartcarofamerica.com/forums/f191/",
		"http://www.smartcarofamerica.com/forums/f219/",
		"http://www.smartcarofamerica.com/forums/f217/",
		"http://www.smartcarofamerica.com/forums/f207/",
		"http://www.smartcarofamerica.com/forums/f206/",
		"http://www.smartcarofamerica.com/forums/f172/",
		"http://www.smartcarofamerica.com/forums/f192/",
		"http://www.smartcarofamerica.com/forums/f214/",
		"http://www.smartcarofamerica.com/forums/f201/",
		"http://www.smartcarofamerica.com/forums/f190/",
		"http://www.smartcarofamerica.com/forums/f162/",
		"http://www.smartcarofamerica.com/forums/f161/",
		"http://www.smartcarofamerica.com/forums/f215/",
		"http://www.smartcarofamerica.com/forums/f163/",
		"http://www.smartcarofamerica.com/forums/f131/",
		"http://www.smartcarofamerica.com/forums/f132/",
		"http://www.smartcarofamerica.com/forums/f133/",
		"http://www.smartcarofamerica.com/forums/f43/",
		"http://www.smartcarofamerica.com/forums/f104/",
		"http://www.smartcarofamerica.com/forums/f106/",
		"http://www.smartcarofamerica.com/forums/f66/",
		"http://www.smartcarofamerica.com/forums/f82/",
		"http://www.smartcarofamerica.com/forums/f107/",
		"http://www.smartcarofamerica.com/forums/f102/",
		"http://www.smartcarofamerica.com/forums/f116/",
		"http://www.smartcarofamerica.com/forums/f103/",
		"http://www.smartcarofamerica.com/forums/f105/",
		"http://www.smartcarofamerica.com/forums/f121/",
		"http://www.smartcarofamerica.com/forums/f73/",
		"http://www.smartcarofamerica.com/forums/f152/",
		"http://www.smartcarofamerica.com/forums/f128/",
		"http://www.smartcarofamerica.com/forums/f150/",
		"http://www.smartcarofamerica.com/forums/f40/",
		"http://www.smartcarofamerica.com/forums/f123/",
		"http://www.smartcarofamerica.com/forums/f89/",
		"http://www.smartcarofamerica.com/forums/f94/",
		"http://www.smartcarofamerica.com/forums/f129/",
		"http://www.smartcarofamerica.com/forums/f81/",
		"http://www.smartcarofamerica.com/forums/f74/",
		"http://www.smartcarofamerica.com/forums/f87/",
		"http://www.smartcarofamerica.com/forums/f153/",
		"http://www.smartcarofamerica.com/forums/f90/",
		"http://www.smartcarofamerica.com/forums/f197/",
		"http://www.smartcarofamerica.com/forums/f124/",
		"http://www.smartcarofamerica.com/forums/f122/",
		"http://www.smartcarofamerica.com/forums/f39/",
		"http://www.smartcarofamerica.com/forums/f120/",
		"http://www.smartcarofamerica.com/forums/f91/",
		"http://www.smartcarofamerica.com/forums/f118/",
		"http://www.smartcarofamerica.com/forums/f46/",
		"http://www.smartcarofamerica.com/forums/f177/",
		"http://www.smartcarofamerica.com/forums/f119/",
		"http://www.smartcarofamerica.com/forums/f92/",
		"http://www.smartcarofamerica.com/forums/f143/",
		"http://www.smartcarofamerica.com/forums/f48/",
		"http://www.smartcarofamerica.com/forums/f199/",
		"http://www.smartcarofamerica.com/forums/f146/",
		"http://www.smartcarofamerica.com/forums/f117/",
		"http://www.smartcarofamerica.com/forums/f126/",
		"http://www.smartcarofamerica.com/forums/f127/",
		"http://www.smartcarofamerica.com/forums/f125/",
		"http://www.smartcarofamerica.com/forums/f108/",
		"http://www.smartcarofamerica.com/forums/f156/",
		"http://www.smartcarofamerica.com/forums/f37/",
		"http://www.smartcarofamerica.com/forums/f45/",
		"http://www.smartcarofamerica.com/forums/f305/",
		"http://www.smartcarofamerica.com/forums/f47/",
		"http://www.smartcarofamerica.com/forums/f44/",
		"http://www.smartcarofamerica.com/forums/f79/",
		"http://www.smartcarofamerica.com/forums/f93/",
		"http://www.smartcarofamerica.com/forums/f113/",
		"http://www.smartcarofamerica.com/forums/f109/",
		"http://www.smartcarofamerica.com/forums/f80/",
		"http://www.smartcarofamerica.com/forums/f114/",
		"http://www.smartcarofamerica.com/forums/f97/",
		"http://www.smartcarofamerica.com/forums/f110/",
		"http://www.smartcarofamerica.com/forums/f83/",
		"http://www.smartcarofamerica.com/forums/f55/",
		"http://www.smartcarofamerica.com/forums/f100/",
		"http://www.smartcarofamerica.com/forums/f56/",
		"http://www.smartcarofamerica.com/forums/f115/",
		"http://www.smartcarofamerica.com/forums/f223/",
		"http://www.smartcarofamerica.com/forums/f41/",
		"http://www.smartcarofamerica.com/forums/f96/",
		"http://www.smartcarofamerica.com/forums/f99/",
		"http://www.smartcarofamerica.com/forums/f5/",
		"http://www.smartcarofamerica.com/forums/f32/",
		"http://www.smartcarofamerica.com/forums/f25/",
		"http://www.smartcarofamerica.com/forums/f19/",
		"http://www.smartcarofamerica.com/forums/f75/",
		"http://www.smartcarofamerica.com/forums/f76/",
		"http://www.smartcarofamerica.com/forums/f147/",
		"http://www.smartcarofamerica.com/forums/f130/",
		"http://www.smartcarofamerica.com/forums/f64/",
		"http://www.smartcarofamerica.com/forums/f77/",
		"http://www.smartcarofamerica.com/forums/f98/",
		"http://www.smartcarofamerica.com/forums/f353/",
		"http://www.smartcarofamerica.com/forums/f369/",
		"http://www.smartcarofamerica.com/forums/f361/",
		"http://www.smartcarofamerica.com/forums/f377/",
		"http://www.smartcarofamerica.com/forums/f385/",
		"http://www.smartcarofamerica.com/forums/f393/",
		"http://www.smartcarofamerica.com/forums/f401/",
		"http://www.smartcarofamerica.com/forums/f409/",
		"http://www.smartcarofamerica.com/forums/f417/",
		"http://www.smartcarofamerica.com/forums/f425/",
		"http://www.smartcarofamerica.com/forums/f433/",
		"http://www.smartcarofamerica.com/forums/f441/",
		"http://www.smartcarofamerica.com/forums/f457/",
		"http://www.smartcarofamerica.com/forums/f465/",
		"http://www.smartcarofamerica.com/forums/f489/",
		"http://www.smartcarofamerica.com/forums/f497/",
		"http://www.smartcarofamerica.com/forums/f505/",
		"http://www.smartcarofamerica.com/forums/f226/",
		"http://www.smartcarofamerica.com/forums/f208/",
		"http://www.smartcarofamerica.com/forums/f210/",
		"http://www.smartcarofamerica.com/forums/f27/",
		"http://www.smartcarofamerica.com/forums/f170/",
		"http://www.smartcarofamerica.com/forums/f198/",
		"http://www.smartcarofamerica.com/forums/f26/",
		"http://www.smartcarofamerica.com/forums/f69/",
		"http://www.smartcarofamerica.com/forums/f70/",
		"http://www.smartcarofamerica.com/forums/f62/",
		"http://www.smartcarofamerica.com/forums/f63/",
		"http://www.smartcarofamerica.com/forums/f169/",
		"http://www.smartcarofamerica.com/forums/f68/",
		"http://www.smartcarofamerica.com/forums/f12/",
		"http://www.smartcarofamerica.com/forums/f84/",
		"http://www.smartcarofamerica.com/forums/f85/",
		"http://www.smartcarofamerica.com/forums/f86/",
		"http://www.smartcarofamerica.com/forums/f186/",
		"http://www.smartcarofamerica.com/forums/f11/",
		"http://www.smartcarofamerica.com/forums/f184/",
		"http://www.smartcarofamerica.com/forums/f78/",
		"http://www.smartcarofamerica.com/forums/f185/",
		"http://www.smartcarofamerica.com/forums/f216/",
		"http://www.smartcarofamerica.com/forums/f7/",
		"http://www.smartcarofamerica.com/forums/f205/",
		"http://www.smartcarofamerica.com/forums/f8/",
		"http://www.smartcarofamerica.com/forums/f9/",
		"http://www.smartcarofamerica.com/forums/f155/",
		"http://www.smartcarofamerica.com/forums/f22/",
		"http://www.smartcarofamerica.com/forums/f167/",
		"http://www.smartcarofamerica.com/forums/f173/",
		"http://www.smartcarofamerica.com/forums/f165/",
		"http://www.smartcarofamerica.com/forums/f166/",
		"http://www.smartcarofamerica.com/forums/f171/",
		"http://www.smartcarofamerica.com/forums/f168/"
        ]
	COUNTRY = "USA"
	THREAD_XPATH = "//a[@class='thread_title_link']"
	THREAD_LINK_XPATH = "./@href"
	LAST_PAGE_XPATH = "(//div[@class='pagenav']//td[@class='vbmenu_control'])[last()]//preceding::a[re:test(@title,'Last Page*') or re:test(@title,'Show results*')][1]/@href"
	PREV_XPATH = "//div[@class='pagenav']//a[@rel='prev']/@href"
	POST_XPATH = "//div[@id='posts']//section[re:test(@id,'post*')]"
	FIELDS = [ 
		{"published_date": {
			"single": True,
			"data_type": "date",
			"concat": False,
			"xpath":".//span[@itemprop='dateCreated']//text()"
		}},
		{"author_name":{
			"single":True,
			"data_type": "string",
			"concat":False,
			"xpath": ".//a[@class='bigusername']//text()"
		}},
		{"content":{
			"single":True,
			"data_type": "string",
			"concat":True,
			"xpath":".//div[re:test(@id,'post_message_*')]//text()"
		}},
		{"permalink": {
			"single": True,
			"data_type": "url",
			"concat": False,
			"xpath": ".//a[contains(text(),'permalink')]//@href"
		}},
		{"title":{
			"single":True,
			"data_type": "string",
			"concat":False,
			"xpath":"//div[@class='breadcrumb']/strong/text()"
		}}       
	]
	CONDITIONS={
		"has_to_have_content":{
			"condition":'"content" in document',
			"exception":'"Content is not defined"'
		},
		"content_cannot_be_empty":{
			"condition":'len(document["content"]) > 0',
			"exception":'"Content cannot be empty"'
		}
	}
#end class
